#!/usr/bin/env python3
"""Generate docs/event-library.md from the catalog, so the manifest can't drift from the code.

Reads the `event(...)` factory calls in Etch/Models/RaceCatalog.swift and the files present in
Etch/Resources/Courses, and writes a per-entry table showing which entries still need a course
file. Run it after editing either; CI runs it with --check to fail on a stale doc.

    python3 scripts/event-library.py           # rewrite the doc
    python3 scripts/event-library.py --check   # exit 1 if the doc is out of date
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CATALOG = os.path.join(ROOT, "Etch/Models/RaceCatalog.swift")
COURSES = os.path.join(ROOT, "Etch/Resources/Courses")
DOC = os.path.join(ROOT, "docs/event-library.md")

# event("id", "Name", "City", "State"|nil, "Country", .discipline, distance, month, day, lat, lon
# Arguments are positional; the distance may be a named constant.
FIELDS = re.compile(
    r'^\s*"(?P<id>[^"]+)"\s*,\s*"(?P<name>[^"]+)"\s*,\s*"(?P<city>[^"]*)"\s*,\s*'
    r'(?:"(?P<state>[^"]*)"|nil)\s*,\s*"(?P<country>[^"]*)"\s*,\s*'
    r'\.(?P<discipline>run|ride|hike)\s*,\s*(?P<distance>[\w_.]+)\s*,\s*'
    r'(?P<month>\d+)\s*,\s*(?P<day>\d+)\s*,',
    re.S,
)
CONSTANT = re.compile(r'private static let (\w+)\s*=\s*([\d_]+(?:\.\d+)?)\b')


def calls(source):
    """Every `event(...)` call body, paren-balanced so nested `c(lat, lon)` doesn't end it."""
    for match in re.finditer(r'\bevent\(', source):
        depth, i = 1, match.end()
        while i < len(source) and depth:
            if source[i] == "(":
                depth += 1
            elif source[i] == ")":
                depth -= 1
            i += 1
        yield source[match.end():i - 1]

MONTHS = ["", "Jan", "Feb", "Mar", "Apr", "May", "Jun",
          "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
TITLES = {"run": "Running", "ride": "Cycling", "hike": "Hikes & Summits"}


def bundled_ids():
    """Event ids with a course file on disk. `boston-2025.gpx` counts as `boston`."""
    ids = set()
    if not os.path.isdir(COURSES):
        return ids
    for entry in os.listdir(COURSES):
        stem, ext = os.path.splitext(entry)
        if ext.lower().lstrip(".") not in ("gpx", "tcx", "fit"):
            continue
        head, _, tail = stem.rpartition("-")
        ids.add(head if head and tail.isdigit() else stem)
    return ids


def parse():
    source = open(CATALOG, encoding="utf-8").read()
    files = bundled_ids()
    constants = {n: float(v.replace("_", "")) for n, v in CONSTANT.findall(source)}
    rows = []
    for body in calls(source):
        m = FIELDS.match(body)
        if not m:
            continue
        e = m.groupdict()
        raw = e["distance"].replace("_", "")
        distance = float(raw) if raw.replace(".", "", 1).isdigit() else constants.get(raw)
        if distance is None:
            print(f'unresolved distance {e["distance"]!r} for {e["id"]}', file=sys.stderr)
            return None
        if e["id"] in files:
            status = "official file"
        elif "traced:" in body:
            status = "traced (approximate)"
        else:
            status = "**needed**"
        rows.append({
            "id": e["id"],
            "name": e["name"],
            "place": ", ".join(p for p in (e["city"], e["state"]) if p),
            "country": e["country"],
            "discipline": e["discipline"],
            "distance": distance,
            "when": f'{MONTHS[int(e["month"])]} {int(e["day"])}',
            "status": status,
        })
    return rows


def distance_label(metres):
    if abs(metres - 42195) < 1:
        return "Marathon"
    if abs(metres - 21097.5) < 1:
        return "Half"
    miles = metres / 1609.344
    if miles >= 30:
        return f"{miles:.0f} mi"
    return f"{miles:.1f} mi"


def render(rows):
    needed = [r for r in rows if r["status"] == "**needed**"]
    out = [
        "# Event library",
        "",
        "<!-- Generated by scripts/event-library.py. Edit the catalog, not this file. -->",
        "",
        f"**{len(rows)} events** — {len(rows) - len(needed)} can draw their own route, "
        f"{len(needed)} still need a course file.",
        "",
        "## How to add a course",
        "",
        "Drop a route file into `Etch/Resources/Courses` and commit it. That's the whole process:",
        "the app target is a synchronized folder, so the file is bundled on the next build with no",
        "Swift change and no Xcode project change. GitHub's web editor works from a phone.",
        "",
        "- `<id>.gpx` — the course for every year (use the **ID** column below).",
        "- `<id>-2025.gpx` — overrides one year, for a race that reroutes.",
        "- `.tcx` and `.fit` work too; the same parsers that read a watch export read these.",
        "",
        "Good sources, roughly in order of trustworthiness: the event's own downloadable GPX (many",
        "publish one on a Course page), the event's Strava or MapMyRun route, a finisher's public",
        "activity, or a hand-traced route from a mapping tool. Anything traced by hand should be",
        "treated as approximate — it is fine for placing and shaping an activity, and not fine to",
        "sell a print from until it's verified against the official course.",
        "",
        "## Status",
        "",
        "- **official file** — a real course file ships with the app.",
        "- **traced (approximate)** — hand-traced from public geography; recognisable, not surveyed.",
        "- **needed** — no geometry. The entry still works: it places the activity in the right city",
        "  with the official distance, and a participant's own file draws the route.",
        "",
    ]
    for key in ("run", "ride", "hike"):
        group = [r for r in rows if r["discipline"] == key]
        if not group:
            continue
        out += [
            f"## {TITLES[key]} ({len(group)})",
            "",
            "| Event | ID | Place | Usual date | Distance | Course |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
        for r in group:
            place = r["place"]
            if r["country"] != "United States":
                place = f'{place}, {r["country"]}' if place else r["country"]
            out.append(
                f'| {r["name"]} | `{r["id"]}` | {place} | {r["when"]} | '
                f'{distance_label(r["distance"])} | {r["status"]} |'
            )
        out.append("")
    return "\n".join(out)


def main():
    rows = parse()
    if rows is None:
        return 1
    if "--json" in sys.argv:
        import json
        for r in rows:
            r["distanceLabel"] = distance_label(r["distance"])
        print(json.dumps(rows, ensure_ascii=False))
        return 0
    text = render(rows)
    check = "--check" in sys.argv
    existing = open(DOC, encoding="utf-8").read() if os.path.exists(DOC) else None
    if check:
        if existing != text:
            print("docs/event-library.md is out of date — run scripts/event-library.py")
            return 1
        print("docs/event-library.md is current")
        return 0
    os.makedirs(os.path.dirname(DOC), exist_ok=True)
    open(DOC, "w", encoding="utf-8").write(text)
    print(f"wrote {DOC}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
